version: '3'
services:
  ########### DJANGO
  django:
    image: dev_django:latest
    restart: always
    build:
      context: .
      dockerfile: docker_django.dockerfile
    volumes:
      - uploads:/django/uploads:rw
      - .:/django
    ports:
      - 8000
    env_file:
      - .env
    environment:
      - DEBUG=True
    container_name: django
    command: 
      - /bin/sh
      - -c 
      - | 
        python wait_for_db.py && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    depends_on:
      - litestream
      - redis
  ########### REDIS
  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - .env
  ########### HUEY
  queue:
    image: dev_queue:latest
    restart: always
    build:
      context: .
      dockerfile: docker_django.dockerfile
    command: 
      - /bin/sh
      - -c 
      - |
        python wait_for_db.py && python manage.py run_huey
    volumes:
      - uploads:/django/uploads:rw
      - ./db:/django/db:rw
      - .:/django
    container_name: huey
    env_file:
      - .env
    environment:
      - DEBUG=True
    depends_on:
      - redis
      - django
      - litestream
########### NGINX
  nginx:
    image: dev_nginx:latest
    restart: always
    build: 
      context: .
      dockerfile: docker_nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
    container_name: nginx
    depends_on:
      - django

########### LITESTREAM
  litestream:
    image: dev_litestream:latest
    build:
      context: .
      dockerfile: docker_litestream.dockerfile
    container_name: litestream
    volumes:
      - ./db:/data/db:rw
    env_file:
      - .env

volumes:
  uploads: