version: '3'
services:
  ########### DJANGO
  django:
    restart: always
    build:
      context: .
      dockerfile: docker_django.dockerfile
    volumes:
      - uploads:/django/uploads:rw
      - db:/django/db:rw
    ports:
      - 8000
    env_file:
      - .env
    container_name: django
    command: 
      - /bin/sh
      - -c 
      - | 
        python clear_db.py && python wait_for_db.py && python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    depends_on:
      - litestream
  ########### REDIS
  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - .env
  ########### HUEY
  queue:
    restart: always
    build:
      context: .
      dockerfile: docker_django.dockerfile
    command: 
      - /bin/sh
      - -c 
      - |
        python wait_for_db.py && python manage.py run_huey
    volumes:
      # - .:/django
      - uploads:/django/uploads:rw
      - db:/django/db:rw
    container_name: huey
    env_file:
      - .env
    depends_on:
      - redis
      - django
########### NGINX
  nginx:
    restart: always
    build: 
      context: .
      dockerfile: docker_nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./_static:/static
    container_name: nginx
    depends_on:
      - django

############ LITESTREAM
  litestream:
    build:
      context: .
      dockerfile: docker_litestream.dockerfile
    ports:
      - 9000
    image: litestream/litestream:latest
    container_name: litestream
    volumes:
      - db:/data/db:rw
    # command: ./start_lights
    env_file:
      - .env

volumes:
  uploads:
  db: