version: '3'
services:
  ########### DJANGO
  django:
    image: 027323396275.dkr.ecr.us-east-1.amazonaws.com/apatosaurus-lambda:latest
    restart: always
    build:
      context: .
      dockerfile: docker_django.dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - DEBUG=False
      - BASE_SITE_URL=https://apatosaurus.io
      - USE_PRODUCTION_DB=True
      - ZAPPA_RUNNING_IN_DOCKER=True
    container_name: apatosaurus-django

  long_task:
    image: 027323396275.dkr.ecr.us-east-1.amazonaws.com/apatosaurus-long-task:latest
    restart: always
    build:
      context: .
      dockerfile: docker_long_task.dockerfile
    env_file:
      - .env
    environment:
      - DEBUG=False
      - BASE_SITE_URL=https://apatosaurus.io
      - USE_PRODUCTION_DB=True
    container_name: long_task