version: '3'
services:
  ########### DJANGO
  django:
    image: 027323396275.dkr.ecr.us-east-1.amazonaws.com/django:latest
    deploy:
      resources:
        reservations:
          cpus: '1.00'
          memory: 2gb
    restart: always
    build:
      context: .
      dockerfile: docker_django.dockerfile
    volumes:
      - temp:/django/temp:rw
    ports:
      - 8000
    env_file:
      - .env
    environment:
      - DEBUG=False
      - BASE_SITE_URL=http://apatosaurus.io
      - USE_PRODUCTION_DB=True
    container_name: django
    command: 
      - /bin/sh
      - -c 
      - | 
        python manage.py migrate && gunicorn -w 2 --bind 0.0.0.0:8000 CONFIG.wsgi --timeout 120
  
  ########### REDIS
  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - .env
  ########### HUEY
  queue:
    image: 027323396275.dkr.ecr.us-east-1.amazonaws.com/queue:latest
    deploy:
      resources:
        reservations:
          cpus: '1.00'
          memory: 2gb
    restart: always
    build:
      context: .
      dockerfile: docker_django.dockerfile
    command: 
      - /bin/sh
      - -c 
      - |
        python manage.py run_huey
    volumes:
      - temp:/django/temp:rw
    container_name: huey
    env_file:
      - .env
    environment:
      - DEBUG=False
      - BASE_SITE_URL=http://apatosaurus.io
      - USE_PRODUCTION_DB=True
    depends_on:
      - redis
      - django
########### NGINX
  nginx:
    image: 027323396275.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
    restart: always
    build: 
      context: .
      dockerfile: docker_nginx.dockerfile
    ports:
      - 80:80
    container_name: nginx
    depends_on:
      - django

volumes:
  temp: