version: '3'
services:
  ########### DJANGO
  django:
    image: 027323396275.dkr.ecr.us-east-1.amazonaws.com/django:latest
    deploy:
      resources:
        reservations:
          cpus: '1.00'
          memory: 2gb
    restart: always
    build:
      context: .
      dockerfile: docker_django.dockerfile
    volumes:
      - uploads:/django/uploads:rw
      - db:/django/db:rw
      - temp:/django/temp:rw
    ports:
      - 8000
    env_file:
      - .env
    environment:
      - DEBUG=False
    container_name: django
    command: 
      - /bin/sh
      - -c 
      - | 
        python wait_for_db.py && python manage.py migrate && gunicorn -w 2 --bind 0.0.0.0:8000 CONFIG.wsgi --timeout 60
    depends_on:
      - litestream
  ########### REDIS
  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - .env
  ########### HUEY
  queue:
    image: 027323396275.dkr.ecr.us-east-1.amazonaws.com/queue:latest
    deploy:
      resources:
        reservations:
          cpus: '1.00'
          memory: 2gb
    restart: always
    build:
      context: .
      dockerfile: docker_django.dockerfile
    command: 
      - /bin/sh
      - -c 
      - |
        python wait_for_db.py && python manage.py run_huey
    volumes:
      - uploads:/django/uploads:rw
      - db:/django/db:rw
      - temp:/django/temp:rw
    container_name: huey
    env_file:
      - .env
    environment:
      - DEBUG=False
    depends_on:
      - litestream
      - redis
      - django
########### NGINX
  nginx:
    image: 027323396275.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
    restart: always
    build: 
      context: .
      dockerfile: docker_nginx.dockerfile
    ports:
      - 80:80
      # - 443:443
    container_name: nginx
    depends_on:
      - django

############ LITESTREAM
  litestream:
    image: 027323396275.dkr.ecr.us-east-1.amazonaws.com/litestream:latest
    build:
      context: .
      dockerfile: docker_litestream.dockerfile
    container_name: litestream
    volumes:
      - db:/data/db:rw
    env_file:
      - .env

volumes:
  uploads:
  db:
  temp: