import { describe, expect, it } from 'vitest';
import { deserializeAlignmentColumns } from './alignment-snapshot';
import { buildCollationProjection } from './collation-projection';
import type { WitnessConfig } from './collation-types';

function makeWitness(
	witnessId: string,
	content: string,
	options?: Partial<Pick<WitnessConfig, 'isBaseText' | 'isExcluded'>>,
): WitnessConfig {
	return {
		witnessId,
		siglum: witnessId,
		transcriptionId: `${witnessId}-tx`,
		sourceVersion: 'v1',
		content,
		tokens: content.split(/\s+/).filter(Boolean).map((token) => ({
			kind: 'text',
			original: token,
			segments: [{ text: token, hasUnclear: false, isPunctuation: false, isSupplied: false }],
			gap: null,
		})),
		treatment: 'inherit',
		isBaseText: options?.isBaseText ?? false,
		isExcluded: options?.isExcluded ?? false,
		overridesDefault: false,
	};
}

describe('buildCollationProjection', () => {
	it('projects active witnesses, source tokens, and variation units only', () => {
		const witnesses = [
			makeWitness('A', 'και θεος', { isBaseText: true }),
			makeWitness('B', 'και λογος'),
			makeWitness('C', 'και θεος', { isExcluded: true }),
		];
		const alignmentColumns = deserializeAlignmentColumns([
			{
				id: 'col-1',
				index: 0,
				merged: false,
				cells: [
					['A', { text: 'και', regularizedText: 'και', alignmentValue: 'και', sourceTokenIds: ['A::source::0'], kind: 'text', gap: null, isOmission: false, isLacuna: false, isRegularized: false, ruleIds: [], regularizationTypes: [] }],
					['B', { text: 'και', regularizedText: 'και', alignmentValue: 'και', sourceTokenIds: ['B::source::0'], kind: 'text', gap: null, isOmission: false, isLacuna: false, isRegularized: false, ruleIds: [], regularizationTypes: [] }],
				],
			},
			{
				id: 'col-2',
				index: 1,
				merged: false,
				cells: [
					['A', { text: 'θεος', regularizedText: 'θεος', alignmentValue: 'θεος', sourceTokenIds: ['A::source::1'], kind: 'text', gap: null, isOmission: false, isLacuna: false, isRegularized: false, ruleIds: [], regularizationTypes: [] }],
					['B', { text: 'λογος', regularizedText: 'λογος', alignmentValue: 'λογος', sourceTokenIds: ['B::source::1'], kind: 'text', gap: null, isOmission: false, isLacuna: false, isRegularized: false, ruleIds: [], regularizationTypes: [] }],
				],
			},
		]);

		const projection = buildCollationProjection({
			witnesses,
			alignmentColumns,
			getBaseWitnessId: () => 'A',
			getBaseTextForVariationUnit: (unitIndex) => (unitIndex === 1 ? 'θεος' : ''),
			getReadingsForUnit: (unitIndex) =>
				unitIndex === 1
					? [
							{
								id: 'r-a',
								order: 0,
								label: 'a',
								text: 'θεος',
								normalizedText: 'θεος',
								witnessIds: ['A'],
								witnessGroups: [{ id: 'g-a', witnessIds: ['A'] }],
								classification: 'unclassified',
								isOmission: false,
								isLacuna: false,
								readingType: null,
								parentReadingId: null,
								isSubreading: false,
								autoGenerated: false,
								derivedFromRuleIds: [],
							},
							{
								id: 'r-b',
								order: 1,
								label: 'b',
								text: 'λογος',
								normalizedText: 'λογος',
								witnessIds: ['B'],
								witnessGroups: [{ id: 'g-b', witnessIds: ['B'] }],
								classification: 'unclassified',
								isOmission: false,
								isLacuna: false,
								readingType: null,
								parentReadingId: null,
								isSubreading: false,
								autoGenerated: false,
								derivedFromRuleIds: [],
							},
					  ]
					: [],
		});

		expect(projection.witnesses.map((row) => row.witnessId)).toEqual(['A', 'B']);
		expect(projection.tokens.filter((row) => row.witnessId === 'A').map((row) => row.tokenText)).toEqual([
			'και',
			'θεος',
		]);
		expect(projection.variationUnits).toHaveLength(1);
		expect(projection.variationUnits[0]).toMatchObject({
			startIndex: 1,
			endIndex: 1,
			baseText: 'θεος',
		});
		expect(projection.variationUnits[0]?.readings.map((reading) => reading.readingText)).toEqual([
			'θεος',
			'λογος',
		]);
	});

	it('projects adjacent variation columns as distinct units unless alignment merged them', () => {
		const witnesses = [
			makeWitness('A', 'και ο λογος', { isBaseText: true }),
			makeWitness('B', 'και του λογου'),
		];
		const alignmentColumns = deserializeAlignmentColumns([
			{
				id: 'col-1',
				index: 0,
				merged: false,
				cells: [
					['A', { text: 'και', regularizedText: 'και', alignmentValue: 'και', sourceTokenIds: ['A::source::0'], kind: 'text', gap: null, isOmission: false, isLacuna: false, isRegularized: false, ruleIds: [], regularizationTypes: [] }],
					['B', { text: 'και', regularizedText: 'και', alignmentValue: 'και', sourceTokenIds: ['B::source::0'], kind: 'text', gap: null, isOmission: false, isLacuna: false, isRegularized: false, ruleIds: [], regularizationTypes: [] }],
				],
			},
			{
				id: 'col-2',
				index: 1,
				merged: false,
				cells: [
					['A', { text: 'ο', regularizedText: 'ο', alignmentValue: 'ο', sourceTokenIds: ['A::source::1'], kind: 'text', gap: null, isOmission: false, isLacuna: false, isRegularized: false, ruleIds: [], regularizationTypes: [] }],
					['B', { text: 'του', regularizedText: 'του', alignmentValue: 'του', sourceTokenIds: ['B::source::1'], kind: 'text', gap: null, isOmission: false, isLacuna: false, isRegularized: false, ruleIds: [], regularizationTypes: [] }],
				],
			},
			{
				id: 'col-3',
				index: 2,
				merged: false,
				cells: [
					['A', { text: 'λογος', regularizedText: 'λογος', alignmentValue: 'λογος', sourceTokenIds: ['A::source::2'], kind: 'text', gap: null, isOmission: false, isLacuna: false, isRegularized: false, ruleIds: [], regularizationTypes: [] }],
					['B', { text: 'λογου', regularizedText: 'λογου', alignmentValue: 'λογου', sourceTokenIds: ['B::source::2'], kind: 'text', gap: null, isOmission: false, isLacuna: false, isRegularized: false, ruleIds: [], regularizationTypes: [] }],
				],
			},
		]);

		const projection = buildCollationProjection({
			witnesses,
			alignmentColumns,
			getBaseWitnessId: () => 'A',
			getBaseTextForVariationUnit: (unitIndex) =>
				unitIndex === 1 ? 'ο' : unitIndex === 2 ? 'λογος' : '',
			getReadingsForUnit: (unitIndex) =>
				unitIndex === 1
					? [
							{
								id: 'r-a',
								order: 0,
								label: 'a',
								text: 'ο',
								normalizedText: 'ο',
								witnessIds: ['A'],
								witnessGroups: [{ id: 'g-a', witnessIds: ['A'] }],
								classification: 'unclassified',
								isOmission: false,
								isLacuna: false,
								readingType: null,
								parentReadingId: null,
								isSubreading: false,
								autoGenerated: false,
								derivedFromRuleIds: [],
							},
							{
								id: 'r-b',
								order: 1,
								label: 'b',
								text: 'του',
								normalizedText: 'του',
								witnessIds: ['B'],
								witnessGroups: [{ id: 'g-b', witnessIds: ['B'] }],
								classification: 'unclassified',
								isOmission: false,
								isLacuna: false,
								readingType: null,
								parentReadingId: null,
								isSubreading: false,
								autoGenerated: false,
								derivedFromRuleIds: [],
							},
						]
					: unitIndex === 2
						? [
								{
									id: 'r-c',
									order: 0,
									label: 'a',
									text: 'λογος',
									normalizedText: 'λογος',
									witnessIds: ['A'],
									witnessGroups: [{ id: 'g-c', witnessIds: ['A'] }],
									classification: 'unclassified',
									isOmission: false,
									isLacuna: false,
									readingType: null,
									parentReadingId: null,
									isSubreading: false,
									autoGenerated: false,
									derivedFromRuleIds: [],
								},
								{
									id: 'r-d',
									order: 1,
									label: 'b',
									text: 'λογου',
									normalizedText: 'λογου',
								witnessIds: ['B'],
								witnessGroups: [{ id: 'g-d', witnessIds: ['B'] }],
								classification: 'unclassified',
								isOmission: false,
								isLacuna: false,
								readingType: null,
								parentReadingId: null,
								isSubreading: false,
								autoGenerated: false,
								derivedFromRuleIds: [],
							},
						]
					: [],
		});

		expect(projection.variationUnits).toHaveLength(2);
		expect(projection.variationUnits[0]).toMatchObject({
			startIndex: 1,
			endIndex: 1,
			baseText: 'ο',
		});
		expect(projection.variationUnits[1]).toMatchObject({
			startIndex: 2,
			endIndex: 2,
			baseText: 'λογος',
		});
	});
});
