import { describe, expect, it } from 'vitest';
import type { ClassifiedReading } from './collation-types';
import { applyDecisions, findOrphanedUnitDecisions } from './collation-decisions';

function reading(
	id: string,
	order: number,
	parentReadingId: string | null = null
): ClassifiedReading {
	return {
		id,
		order,
		label: '',
		text: id,
		normalizedText: id,
		witnessIds: [id],
		witnessGroups: [{ id: `group-${id}`, witnessIds: [id] }],
		classification: 'unclassified',
		isOmission: false,
		isLacuna: false,
		readingType: parentReadingId ? 'ns' : null,
		parentReadingId,
		isSubreading: parentReadingId !== null,
		autoGenerated: parentReadingId !== null,
		derivedFromRuleIds: [],
	};
}

describe('decision overlay', () => {
	it('applies a recorded cross-text attachment over the proposal and relabels readings', () => {
		const result = applyDecisions(
			[reading('alpha', 0), reading('beta', 1), reading('beta-form', 2, 'beta')],
			{ subreadingOf: { alpha: 'beta', 'beta-form': null } }
		);

		expect(
			result.readings.map(entry => ({
				id: entry.id,
				label: entry.label,
				parentReadingId: entry.parentReadingId,
			}))
		).toEqual([
			{ id: 'beta', label: 'a', parentReadingId: null },
			{ id: 'beta-form', label: 'b', parentReadingId: null },
			{ id: 'alpha', label: 'a1', parentReadingId: 'beta' },
		]);
		expect(result.orphanedDecisions).toEqual([]);
	});

	it('reports decisions naming an absent reading or main reading without dropping them', () => {
		const decisions = {
			subreadingOf: { absent: 'alpha', alpha: 'missing-main' },
		};

		expect(applyDecisions([reading('alpha', 0)], decisions).orphanedDecisions).toEqual([
			{
				kind: 'subreadingOf',
				readingId: 'absent',
				mainReadingId: 'alpha',
				missingReadingIds: ['absent'],
			},
			{
				kind: 'subreadingOf',
				readingId: 'alpha',
				mainReadingId: 'missing-main',
				missingReadingIds: ['missing-main'],
			},
		]);
		expect(decisions).toEqual({
			subreadingOf: { absent: 'alpha', alpha: 'missing-main' },
		});
	});

	it('reports decisions belonging to absent units', () => {
		const decisions = new Map<string, import('./collation-decisions').UnitDecisions>([
			['unit:col-1', { subreadingOf: { alpha: 'beta' } }],
			['unit:gone', { subreadingOf: { gamma: null } }],
		]);

		expect(findOrphanedUnitDecisions(decisions, new Set(['unit:col-1']))).toEqual([
			{ unitId: 'unit:gone', decisions: { subreadingOf: { gamma: null } } },
		]);
	});
});
