import { describe, expect, it } from 'vitest';
import { deserializeAlignmentColumns } from './alignment-snapshot';
import {
	buildCollationDocument,
	hydrateCollationDocument,
	parseCollationDocument,
	serializeCollationDocument,
} from './collation-document';
import type { ClassifiedReading, WitnessConfig } from './collation-types';

function makeWitness(witnessId: string, content: string, isBaseText = false): WitnessConfig {
	return {
		witnessId,
		siglum: witnessId,
		transcriptionId: `${witnessId}-tx`,
		sourceVersion: 'v1',
		content,
		tokens: content
			.split(/\s+/)
			.filter(Boolean)
			.map(token => ({
				kind: 'text',
				original: token,
				segments: [
					{
						text: token,
						hasUnclear: false,
						isPunctuation: false,
						isSupplied: false,
					},
				],
				gap: null,
			})),
		treatment: 'inherit',
		isBaseText,
		isExcluded: false,
		overridesDefault: false,
	};
}

function makeClassifiedReading(
	id: string,
	text: string,
	witnessIds: string[],
	order: number
): ClassifiedReading {
	return {
		id,
		order,
		label: '',
		text,
		normalizedText: text,
		witnessIds,
		witnessGroups: [{ id: `g-${id}`, witnessIds }],
		isOmission: false,
		isLacuna: false,
		readingType: null,
		certainty: null,
		parentReadingId: null,
		isSubreading: false,
		autoGenerated: false,
		derivedFromRuleIds: [],
	};
}

describe('collation document', () => {
	it('round-trips semantic state through the persisted document model', () => {
		const document = buildCollationDocument({
			collationId: 'coll-1',
			projectId: 'proj-1',
			projectName: 'Project One',
			phase: 'readings',
			furthestPhase: 'stemma',
			segment: { id: 'segment-1', name: 'John 1:1', members: ['John 1:1'] },
			witnesses: [makeWitness('A', 'θεος', true), makeWitness('B', 'θς')],
			rules: [
				{
					id: 'rule-1',
					pattern: 'θς',
					replacement: 'θεος',
					scope: 'project',
					description: 'nomina sacra',
					enabled: true,
					type: 'ns',
				},
			],
			ignoreWordBreaks: true,
			lowercase: true,
			ignoreTokenWhitespace: true,
			ignorePunctuation: true,
			suppliedTextMode: 'gap',
			segmentation: true,
			alignmentColumns: deserializeAlignmentColumns([
				{
					id: 'col-1',
					index: 0,
					merged: false,
					cells: [
						[
							'A',
							{
								text: 'θεος',
								regularizedText: 'θεος',
								alignmentValue: 'θεος',
								sourceTokenIds: ['A::source::0'],
								kind: 'text',
								gap: null,
								isOmission: false,
								isLacuna: false,
								isRegularized: false,
								ruleIds: [],
								regularizationTypes: [],
							},
						],
						[
							'B',
							{
								text: 'θς',
								regularizedText: 'θεος',
								alignmentValue: 'θεος',
								sourceTokenIds: ['B::source::0'],
								kind: 'text',
								gap: null,
								isOmission: false,
								isLacuna: false,
								isRegularized: true,
								ruleIds: ['rule-1'],
								regularizationTypes: ['ns'],
							},
						],
					],
				},
			]),
			witnessOrder: ['A', 'B'],
			classifiedReadings: new Map([
				[
					'unit:col-1',
					[
						{
							id: 'r-a',
							order: 0,
							label: 'a',
							text: 'θεος',
							normalizedText: 'θεος',
							witnessIds: ['A'],
							witnessGroups: [{ id: 'g-a', witnessIds: ['A'] }],
							isOmission: false,
							isLacuna: false,
							readingType: null,
							certainty: null,
							parentReadingId: null,
							isSubreading: false,
							autoGenerated: false,
							derivedFromRuleIds: [],
						},
						{
							id: 'r-b',
							order: 0,
							label: 'a-sub',
							text: 'θς',
							normalizedText: 'θεος',
							witnessIds: ['B'],
							witnessGroups: [{ id: 'g-b', witnessIds: ['B'] }],
							isOmission: false,
							isLacuna: false,
							readingType: 'ns',
							certainty: null,
							parentReadingId: 'r-a',
							isSubreading: true,
							autoGenerated: true,
							derivedFromRuleIds: ['rule-1'],
						},
					],
				],
			]),
			unitDecisions: new Map([['unit:col-1', { subreadingOf: { 'r-b': 'r-a' } }]]),
			stemmaEdges: new Map([
				[
					'unit:col-1',
					[
						{
							id: 'edge-1',
							sourceReadingId: 'r-a',
							targetReadingId: 'r-b',
							directed: true,
						},
					],
				],
			]),
			alignmentDisplayMode: 'original',
			alignmentLayout: 'variation-units',
		});

		const parsed = parseCollationDocument(serializeCollationDocument(document));
		expect(parsed).not.toBeNull();
		expect(document.apparatus?.units[0]).toMatchObject({
			unitId: 'unit:col-1',
			columnId: 'col-1',
			decisions: { subreadingOf: { 'r-b': 'r-a' } },
		});
		expect(document.apparatus?.units[0]).not.toHaveProperty('unitIndex');
		expect(document.stemma?.units[0]).toMatchObject({
			unitId: 'unit:col-1',
			columnId: 'col-1',
		});
		expect(document.stemma?.units[0]).not.toHaveProperty('unitIndex');
		expect(document).not.toHaveProperty('undoHistory');
		expect(document).not.toHaveProperty('commandHistory');

		const hydrated = hydrateCollationDocument(parsed!);
		expect(hydrated.projectId).toBe('proj-1');
		expect(hydrated.segment).toEqual({
			id: 'segment-1',
			name: 'John 1:1',
			members: ['John 1:1'],
		});
		expect(hydrated.phase).toBe('readings');
		expect(hydrated.furthestPhase).toBe('stemma');
		expect(hydrated.ignoreWordBreaks).toBe(true);
		expect(hydrated.lowercase).toBe(true);
		expect(hydrated.ignoreTokenWhitespace).toBe(true);
		expect(hydrated.ignorePunctuation).toBe(true);
		expect(hydrated.suppliedTextMode).toBe('gap');
		expect(hydrated.alignmentDisplayMode).toBe('original');
		expect(hydrated.alignmentLayout).toBe('variation-units');
		expect(hydrated.witnesses[1]?.tokens[0]?.original).toBe('θς');
		expect(hydrated.alignmentColumns[0]?.cells[1]?.[1].sourceTokenIds).toEqual([
			'B::source::0',
		]);
		expect(hydrated.classifiedReadings).toEqual([]);
		expect(hydrated.unitDecisions).toEqual([
			['unit:col-1', { subreadingOf: { 'r-b': 'r-a' } }],
		]);
		expect(hydrated.stemmaEdges[0]?.[1][0]?.targetReadingId).toBe('r-b');
	});

	it('persists orphaned unit decisions without inventing a positional column id', () => {
		const document = buildCollationDocument({
			collationId: null,
			projectId: null,
			projectName: null,
			phase: 'readings',
			furthestPhase: 'readings',
			segment: { id: 'segment-1', name: 'John 1:1', members: ['John 1:1'] },
			witnesses: [],
			rules: [],
			ignoreWordBreaks: false,
			lowercase: false,
			ignoreTokenWhitespace: true,
			ignorePunctuation: false,
			suppliedTextMode: 'clear',
			segmentation: true,
			alignmentColumns: [],
			witnessOrder: [],
			classifiedReadings: new Map(),
			unitDecisions: new Map([['unit:gone-column', { subreadingOf: { 'r-b': 'r-a' } }]]),
			stemmaEdges: new Map(),
			alignmentDisplayMode: 'regularized',
			alignmentLayout: 'grid',
		});

		expect(document.apparatus?.units).toEqual([
			{
				type: 'variationUnit',
				id: 'unit:gone-column',
				unitId: 'unit:gone-column',
				columnId: null,
				readings: [],
				decisions: { subreadingOf: { 'r-b': 'r-a' } },
			},
		]);
	});

	it('round-trips hand-level corrector witness source variants', () => {
		const corrector: WitnessConfig = {
			...makeWitness('A-c1', 'λογος'),
			siglum: 'A corrector1',
			transcriptionId: 'A-tx',
			kind: 'corrector',
			handId: 'corrector1',
			treatment: 'inherit',
			fullContent: 'λογος',
			fullTokens: makeWitness('tmp-full', 'λογος').tokens,
			fragmentaryContent: 'θς',
			fragmentaryTokens: makeWitness('tmp-frag', 'θς').tokens,
		};

		const hydrated = hydrateCollationDocument(
			buildCollationDocument({
				collationId: 'coll-1',
				projectId: 'proj-1',
				projectName: 'Project One',
				phase: 'setup',
				furthestPhase: 'setup',
				segment: { id: 'segment-1', name: 'John 1:1', members: ['John 1:1'] },
				witnesses: [corrector],
				rules: [],
				ignoreWordBreaks: false,
				lowercase: false,
				ignoreTokenWhitespace: true,
				ignorePunctuation: false,
				suppliedTextMode: 'clear',
				segmentation: true,
				alignmentColumns: [],
				witnessOrder: [],
				classifiedReadings: new Map(),
				unitDecisions: new Map(),
				stemmaEdges: new Map(),
				alignmentDisplayMode: 'regularized',
				alignmentLayout: 'grid',
			})
		);

		expect(hydrated.witnesses[0]).toMatchObject({
			kind: 'corrector',
			handId: 'corrector1',
			fullContent: 'λογος',
			fragmentaryContent: 'θς',
		});
		expect(hydrated.witnesses[0]?.fullTokens?.map(token => token.original)).toEqual(['λογος']);
		expect(hydrated.witnesses[0]?.fragmentaryTokens?.map(token => token.original)).toEqual([
			'θς',
		]);
	});

	it('rejects a segment without a scholar-supplied name', () => {
		expect(() =>
			buildCollationDocument({
				collationId: null,
				projectId: null,
				projectName: null,
				phase: 'setup',
				furthestPhase: 'setup',
				segment: { id: 'segment-1', name: '  ', members: ['John 1:1'] },
				witnesses: [],
				rules: [],
				ignoreWordBreaks: false,
				lowercase: false,
				ignoreTokenWhitespace: true,
				ignorePunctuation: false,
				suppliedTextMode: 'clear',
				segmentation: true,
				alignmentColumns: [],
				witnessOrder: [],
				classifiedReadings: new Map(),
				unitDecisions: new Map(),
				stemmaEdges: new Map(),
				alignmentDisplayMode: 'regularized',
				alignmentLayout: 'grid',
			})
		).toThrow('Collation segment name is required.');
	});

	it('labels the base text reading as the lemma in the persisted apparatus', () => {
		const document = buildCollationDocument({
			collationId: null,
			projectId: null,
			projectName: null,
			phase: 'readings',
			furthestPhase: 'readings',
			segment: { id: 'segment-1', name: 'John 1:1', members: ['John 1:1'] },
			witnesses: [makeWitness('A', 'θεος', true), makeWitness('B', 'κυριος')],
			rules: [],
			ignoreWordBreaks: false,
			lowercase: false,
			ignoreTokenWhitespace: true,
			ignorePunctuation: false,
			suppliedTextMode: 'clear',
			segmentation: true,
			alignmentColumns: [],
			witnessOrder: ['A', 'B'],
			classifiedReadings: new Map([
				[
					'unit:col-1',
					[
						makeClassifiedReading('r-kurios', 'κυριος', ['B', 'C'], 0),
						makeClassifiedReading('r-theos', 'θεος', ['A'], 1),
					],
				],
			]),
			unitDecisions: new Map(),
			stemmaEdges: new Map(),
			alignmentDisplayMode: 'regularized',
			alignmentLayout: 'grid',
		});

		expect(
			document.apparatus?.units[0]?.readings.map(reading => [
				reading.id,
				reading.label,
				reading.order,
			])
		).toEqual([
			['r-theos', 'a', 0],
			['r-kurios', 'b', 1],
		]);
	});

	it('keeps member identifiers opaque while collapsing only exact duplicates', () => {
		const document = buildCollationDocument({
			collationId: null,
			projectId: null,
			projectName: null,
			phase: 'setup',
			furthestPhase: 'setup',
			segment: {
				id: 'segment-1',
				name: 'Romans 1:1',
				members: ['Rom 1:1', 'Rom 1:1', 'rom 1:1', 'Rom 1:1 ', 'Rom 1:1.'],
			},
			witnesses: [],
			rules: [],
			ignoreWordBreaks: false,
			lowercase: false,
			ignoreTokenWhitespace: true,
			ignorePunctuation: false,
			suppliedTextMode: 'clear',
			segmentation: true,
			alignmentColumns: [],
			witnessOrder: [],
			classifiedReadings: new Map(),
			unitDecisions: new Map(),
			stemmaEdges: new Map(),
			alignmentDisplayMode: 'regularized',
			alignmentLayout: 'grid',
		});

		expect(document.setup.segment.members).toEqual([
			'Rom 1:1',
			'rom 1:1',
			'Rom 1:1 ',
			'Rom 1:1.',
		]);
	});
});
