import type { AlignmentCell, AlignmentColumn } from './alignment-snapshot';
import type { ClassifiedReading } from './collation-types';
import { proposeReadingType } from './reading-types';
import {
	buildReadingFamilyGroups,
	classifyWitnessAttestation,
	indexToReadingLabel,
	type ReadingFamilyGroup,
} from './collation-variation-units';

export { indexToReadingLabel } from './collation-variation-units';

function makeWitnessGroups(witnessIds: string[]) {
	if (witnessIds.length === 0) return [];
	return [{ id: crypto.randomUUID(), witnessIds: [...witnessIds] }];
}

export function getReadingFamilyKey(
	reading: Pick<ClassifiedReading, 'normalizedText' | 'text' | 'isOmission' | 'isLacuna'>
): string {
	if (reading.isOmission) return '__OMISSION__';
	if (reading.isLacuna) return '__LACUNA__';
	return reading.normalizedText ?? reading.text ?? '__EMPTY__';
}

export function compareReadingsForPriority(
	a: Pick<ClassifiedReading, 'text' | 'witnessIds'>,
	b: Pick<ClassifiedReading, 'text' | 'witnessIds'>,
	baseWitnessId: string | null
): number {
	const aHasBase = baseWitnessId ? a.witnessIds.includes(baseWitnessId) : false;
	const bHasBase = baseWitnessId ? b.witnessIds.includes(baseWitnessId) : false;
	if (aHasBase !== bHasBase) return aHasBase ? -1 : 1;
	if (a.witnessIds.length !== b.witnessIds.length)
		return b.witnessIds.length - a.witnessIds.length;
	return (a.text ?? '').localeCompare(b.text ?? '');
}

export function compareReadingsForOrder(
	a: Pick<ClassifiedReading, 'order' | 'text' | 'witnessIds'>,
	b: Pick<ClassifiedReading, 'order' | 'text' | 'witnessIds'>,
	baseWitnessId: string | null
): number {
	if (a.order !== b.order) return a.order - b.order;
	return compareReadingsForPriority(a, b, baseWitnessId);
}

export function buildClassifiedReadingsFromFamilyGroups(
	groups: ReadingFamilyGroup[]
): ClassifiedReading[] {
	const readings: ClassifiedReading[] = [];
	for (const [groupIndex, group] of groups.entries()) {
		const members = [group.parent, ...group.children];
		for (const [memberIndex, member] of members.entries()) {
			const parentId = memberIndex === 0 ? null : group.parent.id;
			readings.push({
				id: member.id,
				order: memberIndex === 0 ? groupIndex : memberIndex - 1,
				label: '',
				text: member.originalText,
				normalizedText: member.normalizedText,
				witnessIds: [...member.witnessIds],
				witnessGroups: makeWitnessGroups(member.witnessIds),
				isOmission: member.isOmission,
				isLacuna: member.isLacuna,
				readingType: proposeReadingType(member),
				certainty: null,
				parentReadingId: parentId,
				isSubreading: parentId !== null,
				autoGenerated: parentId !== null,
				derivedFromRuleIds: [...member.ruleIds],
			});
		}
	}
	return readings;
}

export function canonicalizeReadings(
	readings: ClassifiedReading[],
	baseWitnessId: string | null
): ClassifiedReading[] {
	const byId = new Map(readings.map(reading => [reading.id, reading] as const));
	const normalized = readings.map(reading => {
		const parentExists =
			reading.parentReadingId !== null &&
			reading.parentReadingId !== reading.id &&
			byId.has(reading.parentReadingId);
		return {
			...reading,
			parentReadingId: parentExists ? reading.parentReadingId : null,
			isSubreading: parentExists,
			witnessGroups: makeWitnessGroups(reading.witnessIds),
		};
	});

	const readingsByFamilyKey = new Map<string, ClassifiedReading[]>();
	for (const reading of normalized) {
		const key = getReadingFamilyKey(reading);
		const existing = readingsByFamilyKey.get(key) ?? [];
		existing.push(reading);
		readingsByFamilyKey.set(key, existing);
	}

	const updates = new Map<string, ClassifiedReading>();
	for (const family of readingsByFamilyKey.values()) {
		const sortedFamily = [...family].sort((a, b) =>
			compareReadingsForOrder(a, b, baseWitnessId)
		);
		const explicitParent =
			sortedFamily.find(candidate =>
				sortedFamily.some(reading => reading.parentReadingId === candidate.id)
			) ?? null;
		const preferredParent = explicitParent ?? sortedFamily[0] ?? null;
		if (!preferredParent) continue;

		updates.set(preferredParent.id, {
			...preferredParent,
			parentReadingId: null,
			isSubreading: false,
			autoGenerated: preferredParent.autoGenerated && family.length > 1,
		});

		let childOrder = 0;
		for (const reading of sortedFamily) {
			if (reading.id === preferredParent.id) continue;
			const shouldBeSubreading = !reading.isOmission && !reading.isLacuna;
			updates.set(reading.id, {
				...reading,
				order: childOrder,
				parentReadingId: shouldBeSubreading ? preferredParent.id : null,
				isSubreading: shouldBeSubreading,
				autoGenerated: shouldBeSubreading
					? reading.autoGenerated || family.length > 1
					: false,
			});
			childOrder += 1;
		}
	}

	return relabelReadings(
		normalized.map(reading => updates.get(reading.id) ?? reading),
		baseWitnessId
	);
}

export function normalizeReadingOrders(
	readings: ClassifiedReading[],
	baseWitnessId: string | null
): ClassifiedReading[] {
	const primaryReadings = readings.filter(reading => reading.parentReadingId === null);
	const sortedPrimary = [...primaryReadings].sort((a, b) =>
		compareReadingsForOrder(a, b, baseWitnessId)
	);

	const normalizedById = new Map<string, ClassifiedReading>();
	sortedPrimary.forEach((reading, index) => {
		normalizedById.set(reading.id, { ...reading, order: index });
	});

	for (const parent of sortedPrimary) {
		const children = readings
			.filter(reading => reading.parentReadingId === parent.id)
			.sort((a, b) => compareReadingsForOrder(a, b, baseWitnessId));
		children.forEach((reading, index) => {
			normalizedById.set(reading.id, { ...reading, order: index });
		});
	}

	for (const reading of readings) {
		if (!normalizedById.has(reading.id)) {
			normalizedById.set(reading.id, { ...reading, order: reading.order ?? 0 });
		}
	}

	return readings.map(reading => normalizedById.get(reading.id) ?? reading);
}

export function relabelReadings(
	readings: ClassifiedReading[],
	baseWitnessId: string | null,
	lemmaReadingId: string | null = null
): ClassifiedReading[] {
	const normalized = normalizeReadingOrders(readings, baseWitnessId);
	const primaryReadings = normalized.filter(reading => reading.parentReadingId === null);
	// The lemma takes `a`; everything else keeps the base-text-first order, so the reading
	// the scholar compares against stays prominent even when it is not the lemma.
	const sortedPrimary = [...primaryReadings].sort((a, b) => {
		if (a.id === b.id) return 0;
		if (a.id === lemmaReadingId) return -1;
		if (b.id === lemmaReadingId) return 1;
		return compareReadingsForOrder(a, b, baseWitnessId);
	});

	const primaryLabelById = new Map<string, string>();
	const primaryRankById = new Map<string, number>();
	for (const [index, reading] of sortedPrimary.entries()) {
		primaryLabelById.set(reading.id, indexToReadingLabel(index));
		primaryRankById.set(reading.id, index);
	}

	const subreadingsByParent = new Map<string, ClassifiedReading[]>();
	for (const reading of normalized) {
		if (!reading.parentReadingId) continue;
		const existing = subreadingsByParent.get(reading.parentReadingId) ?? [];
		existing.push(reading);
		subreadingsByParent.set(reading.parentReadingId, existing);
	}

	const subLabelById = new Map<string, string>();
	const subRankById = new Map<string, number>();
	for (const [parentId, children] of subreadingsByParent.entries()) {
		const parentLabel = primaryLabelById.get(parentId);
		if (!parentLabel) continue;
		children
			.sort((a, b) => compareReadingsForOrder(a, b, baseWitnessId))
			.forEach((child, index) => {
				subLabelById.set(child.id, `${parentLabel}${index + 1}`);
				subRankById.set(child.id, index);
			});
	}

	return normalized
		.map(reading => ({
			...reading,
			witnessGroups: makeWitnessGroups(reading.witnessIds),
			// `order` is the position this labelling implies, so consumers that sort by it
			// agree with the letters. Elevation is not written back to the stored proposal.
			order:
				reading.parentReadingId === null
					? (primaryRankById.get(reading.id) ?? reading.order)
					: (subRankById.get(reading.id) ?? reading.order),
			label:
				reading.parentReadingId === null
					? (primaryLabelById.get(reading.id) ?? '?')
					: (subLabelById.get(reading.id) ?? '?'),
		}))
		.sort((a, b) => {
			if (a.parentReadingId === null && b.parentReadingId === null) {
				return (primaryRankById.get(a.id) ?? 0) - (primaryRankById.get(b.id) ?? 0);
			}
			if ((a.parentReadingId ?? '') !== (b.parentReadingId ?? '')) {
				if (a.parentReadingId === null && b.parentReadingId !== null) return -1;
				if (a.parentReadingId !== null && b.parentReadingId === null) return 1;
				return (a.parentReadingId ?? '').localeCompare(b.parentReadingId ?? '');
			}
			return a.order - b.order;
		});
}

/**
 * Witnesses that do not testify at a variation unit. Not a reading: they take no letter and
 * never enter ordering. Untranscribed witnesses are held apart because reporting them as
 * non-attestation would assert damage to a manuscript that may be perfectly intact.
 */
export interface NonAttestation {
	witnessIds: string[];
	untranscribedWitnessIds: string[];
}

export interface ReadingProposal {
	readings: ClassifiedReading[];
	nonAttestation: NonAttestation;
}

export function buildReadingProposal({
	columns,
	spanColumnIds,
	sourceWitnessIds,
	baseWitnessId,
}: {
	columns: AlignmentColumn[];
	spanColumnIds: string[];
	sourceWitnessIds: string[];
	baseWitnessId: string | null;
}): ReadingProposal {
	const entries: Array<{ witnessId: string; cells: Array<AlignmentCell | undefined> }> = [];
	const nonAttestation: NonAttestation = { witnessIds: [], untranscribedWitnessIds: [] };

	for (const witnessId of sourceWitnessIds) {
		const cells = columns.map(column => column.cells.get(witnessId));
		switch (classifyWitnessAttestation(cells)) {
			case 'non-attesting':
				nonAttestation.witnessIds.push(witnessId);
				break;
			case 'untranscribed':
				nonAttestation.untranscribedWitnessIds.push(witnessId);
				break;
			default:
				entries.push({ witnessId, cells });
		}
	}

	const groups = buildReadingFamilyGroups({
		entries,
		baseWitnessId,
		columnId: spanColumnIds.join('+'),
	});

	return {
		readings: canonicalizeReadings(
			buildClassifiedReadingsFromFamilyGroups(groups),
			baseWitnessId
		),
		nonAttestation,
	};
}
