import { describe, expect, it } from 'vitest';
import type { ClassifiedReading } from './collation-types';
import { applyDecisions, findOrphanedUnitDecisions } from './collation-decisions';

function reading(
	id: string,
	order: number,
	parentReadingId: string | null = null
): ClassifiedReading {
	return {
		id,
		order,
		label: '',
		text: id,
		normalizedText: id,
		witnessIds: [id],
		witnessGroups: [{ id: `group-${id}`, witnessIds: [id] }],
		isOmission: false,
		isLacuna: false,
		readingType: parentReadingId ? 'nonsense' : null,
		certainty: null,
		parentReadingId,
		isSubreading: parentReadingId !== null,
		autoGenerated: parentReadingId !== null,
		derivedFromRuleIds: [],
	};
}

/** A main reading with the given witnesses, left unordered so priority decides its place. */
function attested(id: string, witnessIds: string[]): ClassifiedReading {
	return {
		...reading(id, 0),
		witnessIds,
		witnessGroups: [{ id: `group-${id}`, witnessIds }],
	};
}

describe('decision overlay', () => {
	it('applies a recorded cross-text attachment over the proposal and relabels readings', () => {
		const result = applyDecisions(
			[reading('alpha', 0), reading('beta', 1), reading('beta-form', 2, 'beta')],
			{ subreadingOf: { alpha: 'beta', 'beta-form': null } }
		);

		expect(
			result.readings.map(entry => ({
				id: entry.id,
				label: entry.label,
				parentReadingId: entry.parentReadingId,
			}))
		).toEqual([
			{ id: 'beta', label: 'a', parentReadingId: null },
			{ id: 'beta-form', label: 'b', parentReadingId: null },
			{ id: 'alpha', label: 'a1', parentReadingId: 'beta' },
		]);
		expect(result.orphanedDecisions).toEqual([]);
	});

	it('reports decisions naming an absent reading or main reading without dropping them', () => {
		const decisions = {
			subreadingOf: { absent: 'alpha', alpha: 'missing-main' },
		};

		expect(applyDecisions([reading('alpha', 0)], decisions).orphanedDecisions).toEqual([
			{
				kind: 'subreadingOf',
				readingId: 'absent',
				mainReadingId: 'alpha',
				missingReadingIds: ['absent'],
			},
			{
				kind: 'subreadingOf',
				readingId: 'alpha',
				mainReadingId: 'missing-main',
				missingReadingIds: ['missing-main'],
			},
		]);
		expect(decisions).toEqual({
			subreadingOf: { absent: 'alpha', alpha: 'missing-main' },
		});
	});

	it('derives the lemma from the base text when nothing is recorded', () => {
		const result = applyDecisions(
			[attested('alpha', ['base']), attested('beta', ['w1', 'w2'])],
			{},
			{ baseWitnessId: 'base' }
		);

		expect(result.lemmaReadingId).toBe('alpha');
		expect(result.baseTextReadingId).toBe('alpha');
		expect(result.needsLemmaDecision).toBe(false);
		expect(result.readings.map(entry => [entry.id, entry.label])).toEqual([
			['alpha', 'a'],
			['beta', 'b'],
		]);
	});

	it('elevates a designated reading to a and keeps the base-text reading ahead of the rest', () => {
		const result = applyDecisions(
			[
				attested('alpha', ['base']),
				attested('beta', ['w1']),
				attested('gamma', ['w2', 'w3']),
			],
			{ lemmaReadingId: 'gamma' },
			{ baseWitnessId: 'base' }
		);

		expect(result.lemmaReadingId).toBe('gamma');
		expect(result.baseTextReadingId).toBe('alpha');
		expect(result.readings.map(entry => [entry.id, entry.label])).toEqual([
			['gamma', 'a'],
			['alpha', 'b'],
			['beta', 'c'],
		]);
	});

	it('gives elevated readings an order that agrees with their labels', () => {
		const result = applyDecisions(
			[
				attested('alpha', ['base']),
				attested('beta', ['w1']),
				attested('gamma', ['w2', 'w3']),
			],
			{ lemmaReadingId: 'gamma' },
			{ baseWitnessId: 'base' }
		);

		expect(result.readings.map(entry => [entry.id, entry.label, entry.order])).toEqual([
			['gamma', 'a', 0],
			['alpha', 'b', 1],
			['beta', 'c', 2],
		]);
		expect([...result.readings].sort((a, b) => a.order - b.order)).toEqual(result.readings);
	});

	it('never promotes the majority reading where the base text does not attest', () => {
		const result = applyDecisions(
			[
				{ ...attested('alpha', ['base']), isLacuna: true },
				attested('beta', ['w1']),
				attested('gamma', ['w2', 'w3']),
			],
			{},
			{ baseWitnessId: 'base' }
		);

		expect(result.lemmaReadingId).toBeNull();
		expect(result.needsLemmaDecision).toBe(true);
		// `gamma` leads the provisional witness-count order but is not thereby the lemma.
		expect(result.readings[0]?.id).toBe('gamma');
	});

	it('reports a unit as needing a lemma decision when the base text does not attest', () => {
		const result = applyDecisions(
			[
				{ ...attested('alpha', ['base']), isLacuna: true },
				attested('beta', ['w1']),
				attested('gamma', ['w2', 'w3']),
			],
			{},
			{ baseWitnessId: 'base' }
		);

		expect(result.lemmaReadingId).toBeNull();
		expect(result.baseTextReadingId).toBeNull();
		expect(result.needsLemmaDecision).toBe(true);
		expect(result.readings.map(entry => entry.label).sort()).toEqual(['a', 'b', 'c']);
	});

	it('clears the report once a lemma is designated at such a unit', () => {
		const proposal = [
			{ ...attested('alpha', ['base']), isLacuna: true },
			attested('beta', ['w1']),
		];

		const result = applyDecisions(
			proposal,
			{ lemmaReadingId: 'beta' },
			{ baseWitnessId: 'base' }
		);

		expect(result.needsLemmaDecision).toBe(false);
		expect(result.readings.find(entry => entry.id === 'beta')?.label).toBe('a');
	});

	it('reports a lemma decision naming an absent reading and falls back to the base text', () => {
		const result = applyDecisions(
			[attested('alpha', ['base'])],
			{ lemmaReadingId: 'gone' },
			{ baseWitnessId: 'base' }
		);

		expect(result.orphanedDecisions).toEqual([
			{ kind: 'lemma', readingId: 'gone', missingReadingIds: ['gone'] },
		]);
		expect(result.lemmaReadingId).toBe('alpha');
	});

	it('reports a source decision naming an absent reading rather than dropping it', () => {
		const result = applyDecisions([reading('alpha', 0)], {
			sourceDecision: { alpha: { kind: 'unclear' }, gone: { kind: 'unclear' } },
		});

		expect(result.orphanedDecisions).toEqual([
			{
				kind: 'sourceDecision',
				readingId: 'gone',
				sourceDecision: { kind: 'unclear' },
				missingReadingIds: ['gone'],
			},
		]);
	});

	it('reports decisions belonging to absent units', () => {
		const decisions = new Map<string, import('./collation-decisions').UnitDecisions>([
			['unit:col-1', { subreadingOf: { alpha: 'beta' } }],
			['unit:gone', { subreadingOf: { gamma: null } }],
		]);

		expect(findOrphanedUnitDecisions(decisions, new Set(['unit:col-1']))).toEqual([
			{ unitId: 'unit:gone', decisions: { subreadingOf: { gamma: null } } },
		]);
	});
});

describe('reading type and certainty decisions', () => {
	it('outranks the proposed type and records "no type" distinctly from undecided', () => {
		const proposal = [reading('alpha', 0), reading('alpha-form', 1, 'alpha')];

		const decided = applyDecisions(proposal, {
			readingType: { alpha: 'apparent', 'alpha-form': null },
		});

		expect(decided.readings.map(entry => [entry.id, entry.readingType])).toEqual([
			['alpha', 'apparent'],
			['alpha-form', null],
		]);
		expect(
			applyDecisions(proposal, {}).readings.map(entry => [entry.id, entry.readingType])
		).toEqual([
			['alpha', null],
			['alpha-form', 'nonsense'],
		]);
	});

	it('carries a project-supplied type value it does not recognise', () => {
		const decided = applyDecisions([reading('alpha', 0)], {
			readingType: { alpha: 'itacism' },
		});

		expect(decided.readings[0]?.readingType).toBe('itacism');
	});

	it('applies certainty independently of the reading type', () => {
		const decided = applyDecisions([reading('alpha', 0), reading('beta', 1)], {
			readingType: { alpha: 'apparent' },
			certainty: { alpha: 'low', beta: 0.4 },
		});

		expect(
			decided.readings.map(entry => [entry.id, entry.readingType, entry.certainty])
		).toEqual([
			['alpha', 'apparent', 'low'],
			['beta', null, 0.4],
		]);
	});

	it('reports type and certainty decisions naming an absent reading', () => {
		const result = applyDecisions([reading('alpha', 0)], {
			readingType: { absent: 'nonsense' },
			certainty: { absent: 'high' },
		});

		expect(result.orphanedDecisions).toEqual([
			{
				kind: 'readingType',
				readingId: 'absent',
				readingType: 'nonsense',
				missingReadingIds: ['absent'],
			},
			{
				kind: 'certainty',
				readingId: 'absent',
				certainty: 'high',
				missingReadingIds: ['absent'],
			},
		]);
	});
});
