export type CollationPhase = 'setup' | 'regularization' | 'alignment' | 'readings' | 'stemma';

export type RuleScope = 'project' | 'verse';

export type RegularizationType = 'none' | 'ns';

export type SuppliedTextMode = 'clear' | 'gap';

export type AlignmentCellKind = 'text' | 'gap' | 'untranscribed' | 'omission';

export interface GapMetadata {
	source: 'gap' | 'untranscribed' | 'supplied';
	reason: string;
	unit: string;
	extent: string;
}

export interface WitnessTextSegment {
	text: string;
	hasUnclear: boolean;
	isPunctuation: boolean;
	isSupplied: boolean;
}

export interface WitnessSourceToken {
	kind: 'text' | 'gap' | 'untranscribed';
	original: string;
	segments: WitnessTextSegment[];
	gap: GapMetadata | null;
}

export type WitnessTreatment = 'inherit' | 'full' | 'fragmentary';

export type WitnessKind = 'firsthand' | 'corrector';

export interface WitnessConfig {
	witnessId: string;
	siglum: string;
	transcriptionId: string;
	kind?: WitnessKind;
	handId?: string;
	sourceVersion?: string;
	content: string;
	tokens: WitnessSourceToken[];
	fullContent?: string;
	fullTokens?: WitnessSourceToken[];
	fragmentaryContent?: string;
	fragmentaryTokens?: WitnessSourceToken[];
	treatment: WitnessTreatment;
	isBaseText: boolean;
	isExcluded: boolean;
	overridesDefault: boolean;
}

export interface StemmaEdge {
	id: string;
	sourceReadingId: string;
	targetReadingId: string;
	directed: boolean;
}

export interface RegularizationRule {
	id: string;
	pattern: string;
	replacement: string;
	scope: RuleScope;
	description: string;
	enabled: boolean;
	type: RegularizationType;
}

export interface RegularizedToken {
	original: string;
	originalSegments: WitnessTextSegment[];
	regularized: string | null;
	alignmentValue: string | null;
	ruleIds: string[];
	types: RegularizationType[];
	kind: AlignmentCellKind;
	gap: GapMetadata | null;
	hasUnclear: boolean;
	isPunctuation: boolean;
	isSupplied: boolean;
}

export type ReadingClassification =
	| 'unclassified'
	| 'omit'
	| 'add'
	| 'substitute'
	| 'transpose'
	| 'orthographic';

export interface ReadingWitnessGroup {
	id: string;
	witnessIds: string[];
}

export interface ClassifiedReading {
	id: string;
	order: number;
	label: string;
	text: string | null;
	normalizedText: string | null;
	witnessIds: string[];
	witnessGroups: ReadingWitnessGroup[];
	classification: ReadingClassification;
	isOmission: boolean;
	isLacuna: boolean;
	readingType: RegularizationType | null;
	parentReadingId: string | null;
	isSubreading: boolean;
	autoGenerated: boolean;
	derivedFromRuleIds: string[];
}

export type AlignmentDisplayMode = 'regularized' | 'original';

export type AlignmentLayout = 'grid' | 'variation-units';

export interface ProjectCollationSettings {
	regularizationRules?: RegularizationRule[];
	ignoreWordBreaks?: boolean;
	lowercase?: boolean;
	ignoreTokenWhitespace?: boolean;
	ignorePunctuation?: boolean;
	suppliedTextMode?: SuppliedTextMode;
	segmentation?: boolean;
	transcriptionWitnessTreatments?: Record<string, WitnessTreatment>;
	transcriptionWitnessExcludedHands?: Record<string, string[]>;
}
