import { describe, expect, it } from 'vitest';
import { deserializeAlignmentColumns } from './alignment-snapshot';
import {
	buildCollationDocument,
	hydrateCollationDocument,
	parseCollationDocument,
	serializeCollationDocument,
} from './collation-document';
import type { WitnessConfig } from './collation-types';

function makeWitness(witnessId: string, content: string, isBaseText = false): WitnessConfig {
	return {
		witnessId,
		siglum: witnessId,
		transcriptionId: `${witnessId}-tx`,
		sourceVersion: 'v1',
		content,
		tokens: content.split(/\s+/).filter(Boolean).map((token) => ({
			kind: 'text',
			original: token,
			segments: [
				{
					text: token,
					hasUnclear: false,
					isPunctuation: false,
					isSupplied: false,
				},
			],
			gap: null,
		})),
		treatment: 'inherit',
		isBaseText,
		isExcluded: false,
		overridesDefault: false,
	};
}

describe('collation document', () => {
	it('round-trips semantic state through the persisted document model', () => {
		const document = buildCollationDocument({
			collationId: 'coll-1',
			projectId: 'proj-1',
			projectName: 'Project One',
			phase: 'readings',
			furthestPhase: 'stemma',
			selectedVerse: {
				identifier: 'John 1:1',
				book: 'John',
				chapter: '1',
				verse: '1',
				count: 2,
			},
			selectedBook: 'John',
			selectedChapter: '1',
			selectedVerseNum: '1',
			witnesses: [makeWitness('A', 'θεος', true), makeWitness('B', 'θς')],
			rules: [
				{
					id: 'rule-1',
					pattern: 'θς',
					replacement: 'θεος',
					scope: 'project',
					description: 'nomina sacra',
					enabled: true,
					type: 'ns',
				},
			],
			ignoreWordBreaks: true,
			lowercase: true,
			ignoreTokenWhitespace: true,
			ignorePunctuation: true,
			suppliedTextMode: 'gap',
			segmentation: true,
			alignmentColumns: deserializeAlignmentColumns([
				{
					id: 'col-1',
					index: 0,
					merged: false,
					cells: [
						[
							'A',
							{
								text: 'θεος',
								regularizedText: 'θεος',
								alignmentValue: 'θεος',
								sourceTokenIds: ['A::source::0'],
								kind: 'text',
								gap: null,
								isOmission: false,
								isLacuna: false,
								isRegularized: false,
								ruleIds: [],
								regularizationTypes: [],
							},
						],
						[
							'B',
							{
								text: 'θς',
								regularizedText: 'θεος',
								alignmentValue: 'θεος',
								sourceTokenIds: ['B::source::0'],
								kind: 'text',
								gap: null,
								isOmission: false,
								isLacuna: false,
								isRegularized: true,
								ruleIds: ['rule-1'],
								regularizationTypes: ['ns'],
							},
						],
					],
				},
			]),
			witnessOrder: ['A', 'B'],
			classifiedReadings: new Map([
				[
					'0',
					[
						{
							id: 'r-a',
							order: 0,
							label: 'a',
							text: 'θεος',
							normalizedText: 'θεος',
							witnessIds: ['A'],
							witnessGroups: [{ id: 'g-a', witnessIds: ['A'] }],
							classification: 'unclassified',
							isOmission: false,
							isLacuna: false,
							readingType: null,
							parentReadingId: null,
							isSubreading: false,
							autoGenerated: false,
							derivedFromRuleIds: [],
						},
						{
							id: 'r-b',
							order: 0,
							label: 'a-sub',
							text: 'θς',
							normalizedText: 'θεος',
							witnessIds: ['B'],
							witnessGroups: [{ id: 'g-b', witnessIds: ['B'] }],
							classification: 'orthographic',
							isOmission: false,
							isLacuna: false,
							readingType: 'ns',
							parentReadingId: 'r-a',
							isSubreading: true,
							autoGenerated: true,
							derivedFromRuleIds: ['rule-1'],
						},
					],
				],
			]),
			stemmaEdges: new Map([
				[
					'0',
					[
						{
							id: 'edge-1',
							sourceReadingId: 'r-a',
							targetReadingId: 'r-b',
							directed: true,
						},
					],
				],
			]),
			alignmentDisplayMode: 'original',
			alignmentLayout: 'variation-units',
		});

		const parsed = parseCollationDocument(serializeCollationDocument(document));
		expect(parsed).not.toBeNull();

		const hydrated = hydrateCollationDocument(parsed!);
		expect(hydrated.projectId).toBe('proj-1');
		expect(hydrated.phase).toBe('readings');
		expect(hydrated.furthestPhase).toBe('stemma');
		expect(hydrated.ignoreWordBreaks).toBe(true);
		expect(hydrated.lowercase).toBe(true);
		expect(hydrated.ignoreTokenWhitespace).toBe(true);
		expect(hydrated.ignorePunctuation).toBe(true);
		expect(hydrated.suppliedTextMode).toBe('gap');
		expect(hydrated.alignmentDisplayMode).toBe('original');
		expect(hydrated.alignmentLayout).toBe('variation-units');
		expect(hydrated.witnesses[1]?.tokens[0]?.original).toBe('θς');
		expect(hydrated.alignmentColumns[0]?.cells[1]?.[1].sourceTokenIds).toEqual(['B::source::0']);
		expect(hydrated.classifiedReadings[0]?.[1][1]?.readingType).toBe('ns');
		expect(hydrated.stemmaEdges[0]?.[1][0]?.targetReadingId).toBe('r-b');
	});

	it('round-trips hand-level corrector witness source variants', () => {
		const corrector: WitnessConfig = {
			...makeWitness('A-c1', 'λογος'),
			siglum: 'A corrector1',
			transcriptionId: 'A-tx',
			kind: 'corrector',
			handId: 'corrector1',
			treatment: 'inherit',
			fullContent: 'λογος',
			fullTokens: makeWitness('tmp-full', 'λογος').tokens,
			fragmentaryContent: 'θς',
			fragmentaryTokens: makeWitness('tmp-frag', 'θς').tokens,
		};

		const hydrated = hydrateCollationDocument(
			buildCollationDocument({
				collationId: 'coll-1',
				projectId: 'proj-1',
				projectName: 'Project One',
				phase: 'setup',
				furthestPhase: 'setup',
				selectedVerse: null,
				selectedBook: '',
				selectedChapter: '',
				selectedVerseNum: '',
				witnesses: [corrector],
				rules: [],
				ignoreWordBreaks: false,
				lowercase: false,
				ignoreTokenWhitespace: true,
				ignorePunctuation: false,
				suppliedTextMode: 'clear',
				segmentation: true,
				alignmentColumns: [],
				witnessOrder: [],
				classifiedReadings: new Map(),
				stemmaEdges: new Map(),
				alignmentDisplayMode: 'regularized',
				alignmentLayout: 'grid',
			}),
		);

		expect(hydrated.witnesses[0]).toMatchObject({
			kind: 'corrector',
			handId: 'corrector1',
			fullContent: 'λογος',
			fragmentaryContent: 'θς',
		});
		expect(hydrated.witnesses[0]?.fullTokens?.map((token) => token.original)).toEqual(['λογος']);
		expect(hydrated.witnesses[0]?.fragmentaryTokens?.map((token) => token.original)).toEqual(['θς']);
	});
});
