import { relabelReadings } from './collation-reading-proposal';
import type { ClassifiedReading } from './collation-types';

export interface UnitDecisions {
	subreadingOf?: Record<string, string | null>;
}

export interface OrphanedDecision {
	kind: 'subreadingOf';
	readingId: string;
	mainReadingId: string | null;
	missingReadingIds: string[];
}

export interface OrphanedUnitDecision {
	unitId: string;
	decisions: UnitDecisions;
}

export function cloneUnitDecisions(decisions: UnitDecisions | undefined): UnitDecisions {
	return decisions?.subreadingOf ? { subreadingOf: { ...decisions.subreadingOf } } : {};
}

export function applyDecisions(
	proposal: ClassifiedReading[],
	decisions: UnitDecisions
): { readings: ClassifiedReading[]; orphanedDecisions: OrphanedDecision[] } {
	const readingIds = new Set(proposal.map(reading => reading.id));
	const orphanedDecisions: OrphanedDecision[] = [];
	const applicable = new Map<string, string | null>();

	for (const [readingId, mainReadingId] of Object.entries(decisions.subreadingOf ?? {})) {
		const missingReadingIds = [readingId, mainReadingId].filter(
			(id): id is string => id !== null && !readingIds.has(id)
		);
		if (missingReadingIds.length > 0) {
			orphanedDecisions.push({
				kind: 'subreadingOf',
				readingId,
				mainReadingId,
				missingReadingIds,
			});
			continue;
		}
		applicable.set(readingId, mainReadingId);
	}
	const readings = proposal.map(reading => {
		if (!applicable.has(reading.id)) return { ...reading };
		const parentReadingId = applicable.get(reading.id) ?? null;
		return {
			...reading,
			parentReadingId,
			isSubreading: parentReadingId !== null,
			autoGenerated: false,
		};
	});

	return {
		readings: relabelReadings(readings, null),
		orphanedDecisions,
	};
}

export function findOrphanedUnitDecisions(
	decisions: ReadonlyMap<string, UnitDecisions>,
	liveUnitIds: ReadonlySet<string>
): OrphanedUnitDecision[] {
	return [...decisions.entries()]
		.filter(([unitId]) => !liveUnitIds.has(unitId))
		.map(([unitId, unitDecisions]) => ({
			unitId,
			decisions: cloneUnitDecisions(unitDecisions),
		}));
}
