# Generated by Django 4.1.7 on 2024-01-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transcription',
            options={'ordering': ['date_created']},
        ),
    ]
