# Generated by Django 4.2.11 on 2024-05-10 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0018_appindex_rdgindex'),
        ('transcriptions', '0002_alter_transcription_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='witness',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='collation.witness'),
        ),
    ]
