import { coerceTranscriptionDocument } from '$lib/client/transcription/content';
import type { CollationDocument as SemanticCollationDocument } from '$lib/client/collation/collation-document';
import { exportTEIDocument } from '$lib/tei/tei-exporter';

import type { ProjectTranscriptionPayload } from './project-transcription';

export function transcriptionDocumentToTei(document: ProjectTranscriptionPayload): string {
	const transcription = coerceTranscriptionDocument(document.content_json);
	if (!transcription) {
		throw new Error(`Project transcription ${document.project_transcription_id} has invalid content.`);
	}
	return exportTEIDocument(transcription, {
		title: document.title,
		transcriber: document.transcriber,
		repository: document.repository,
		settlement: document.settlement,
		idno: document.siglum,
		language: document.language,
	});
}

export function collationDocumentToTei(document: SemanticCollationDocument): string {
	const title = document.meta.projectName
		? `${document.meta.projectName} Collation`
		: 'Apatosaurus Collation';
	const verseIdentifier = selectedVerseIdentifier(document);
	const witnesses = document.setup.witnesses;
	const witnessIds = new Map(witnesses.map(witness => [witness.id, witnessXmlId(witness.id)]));
	const witnessList = witnesses
		.map(
			witness =>
				`          <witness xml:id="${escapeAttribute(witnessXmlId(witness.id))}" n="${escapeAttribute(witness.siglum)}"/>`
		)
		.join('\n');
	const apparatus = (document.apparatus?.units ?? [])
		.map(unit => serializeVariationUnit(unit, verseIdentifier, witnessIds))
		.join('\n');
	return `<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>${escapeText(title)}</title>
      </titleStmt>
      <publicationStmt>
        <p>Derived collation apparatus generated by Apatosaurus.</p>
      </publicationStmt>
      <sourceDesc>
        <listWit>
${witnessList}
        </listWit>
      </sourceDesc>
    </fileDesc>
  </teiHeader>
  <text xml:lang="grc">
    <body>
      <div type="collation" n="${escapeAttribute(verseIdentifier)}">
        <ab xml:id="${escapeAttribute(xmlId(`${verseIdentifier}-APP`))}">
${apparatus}
        </ab>
      </div>
    </body>
  </text>
</TEI>`;
}

function serializeVariationUnit(
	unit: NonNullable<SemanticCollationDocument['apparatus']>['units'][number],
	verseIdentifier: string,
	witnessIds: Map<string, string>
): string {
	const readings = [...unit.readings].sort((left, right) => left.order - right.order);
	const [lemma, ...variantReadings] = readings;
	const position = String(unit.unitIndex + 1);
	const serializedLemma = lemma
		? serializeReading('lem', lemma, 0, witnessIds)
		: '          <lem type="om"/>';
	const serializedReadings = variantReadings
		.map((reading, index) => serializeReading('rdg', reading, index + 1, witnessIds))
		.join('\n');
	return `          <app from="${escapeAttribute(position)}" n="${escapeAttribute(verseIdentifier)}" to="${escapeAttribute(position)}" type="main">
${serializedLemma}${serializedReadings ? `\n${serializedReadings}` : ''}
            <note><label>${escapeText(`${verseIdentifier}/${position}`)}</label></note>
          </app>`;
}

function serializeReading(
	tag: 'lem' | 'rdg',
	reading: NonNullable<SemanticCollationDocument['apparatus']>['units'][number]['readings'][number],
	sequence: number,
	witnessIds: Map<string, string>
): string {
	const attrs = [
		tag === 'rdg' ? `n="${escapeAttribute(reading.label || String(sequence))}"` : '',
		tag === 'rdg' ? `varSeq="${sequence}"` : '',
		readingTypeAttribute(reading),
		witnessAttribute(reading.witnessIds, witnessIds),
	]
		.filter(Boolean)
		.join(' ');
	const text = reading.isOmission ? '' : reading.isLacuna ? 'lac' : (reading.text ?? '');
	const prefix = attrs ? `<${tag} ${attrs}` : `<${tag}`;
	return text ? `            ${prefix}>${escapeText(text)}</${tag}>` : `            ${prefix}/>`;
}

function readingTypeAttribute(
	reading: NonNullable<SemanticCollationDocument['apparatus']>['units'][number]['readings'][number]
): string {
	if (reading.isOmission) return 'type="om"';
	if (reading.isLacuna) return 'type="lac"';
	return reading.readingType ? `type="${escapeAttribute(reading.readingType)}"` : '';
}

function witnessAttribute(witnesses: string[], witnessIds: Map<string, string>): string {
	const refs = witnesses.map(witness => `#${witnessIds.get(witness) ?? witnessXmlId(witness)}`);
	return refs.length > 0 ? `wit="${escapeAttribute(refs.join(' '))}"` : '';
}

function selectedVerseIdentifier(document: SemanticCollationDocument): string {
	const selected = document.setup.selectedVerse;
	if (selected?.identifier) return selected.identifier;
	return [document.setup.selectedBook, document.setup.selectedChapter, document.setup.selectedVerseNum]
		.filter(Boolean)
		.join(' ') || 'collation';
}

function witnessXmlId(value: string): string {
	return xmlId(`wit-${value}`);
}

function xmlId(value: string): string {
	const normalized = value.trim().replace(/[^A-Za-z0-9_.-]+/g, '-');
	if (!normalized) return 'generated-id';
	return /^[A-Za-z_]/.test(normalized) ? normalized : `id-${normalized}`;
}

function escapeText(value: string): string {
	return value.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escapeAttribute(value: string): string {
	return escapeText(value).replace(/"/g, '&quot;');
}
