# Generated by Django 6.0.2 on 2026-03-05 19:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcription', '0002_transcription_content_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('charter', models.TextField(blank=True, default='')),
                ('collation_settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-_djazzkit_updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('role', models.CharField(default='member', max_length=32)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='project.project', to_field='_djazzkit_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'user'), name='uniq_project_membership')],
            },
        ),
        migrations.CreateModel(
            name='ProjectObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_uid', models.UUIDField(db_index=True)),
                ('object_type', models.CharField(max_length=32)),
                ('permission', models.CharField(default='write', max_length=32)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_permissions', to='project.project', to_field='_djazzkit_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_object_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'user', 'object_uid'), name='uniq_project_object_perm')],
            },
        ),
        migrations.CreateModel(
            name='ProjectTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_links', to='project.project', to_field='_djazzkit_id')),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='transcription.transcription', to_field='_djazzkit_id')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'transcription'), name='uniq_project_transcription')],
            },
        ),
    ]
