# Generated by Django 6.0.2 on 2026-03-02 20:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('verse_identifier', models.CharField(db_index=True, max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-_djazzkit_updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollationArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('artifact_type', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collation', models.ForeignKey(on_delete=models.CASCADE, to='collation.collation', to_field='_djazzkit_id')),
            ],
            options={
                'ordering': ['-_djazzkit_updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollationVariationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('unit_type', models.CharField(max_length=32)),
                ('base_text', models.TextField(blank=True, default='')),
                ('collation', models.ForeignKey(on_delete=models.CASCADE, to='collation.collation', to_field='_djazzkit_id')),
            ],
            options={
                'ordering': ['-_djazzkit_updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CollationReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('reading_order', models.IntegerField(default=0)),
                ('reading_text', models.TextField(blank=True, default='')),
                ('is_omission', models.BooleanField(default=False)),
                ('is_lacuna', models.BooleanField(default=False)),
                ('variation_unit', models.ForeignKey(on_delete=models.CASCADE, to='collation.collationvariationunit', to_field='_djazzkit_id')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('variation_unit', 'reading_order'), name='uniq_reading_per_variation_order')],
            },
        ),
        migrations.CreateModel(
            name='CollationReadingWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('witness_id', models.CharField(db_index=True, max_length=64)),
                ('reading', models.ForeignKey(on_delete=models.CASCADE, to='collation.collationreading', to_field='_djazzkit_id')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reading', 'witness_id'), name='uniq_reading_witness_assignment')],
            },
        ),
        migrations.CreateModel(
            name='CollationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('witness_id', models.CharField(db_index=True, max_length=64)),
                ('token_index', models.IntegerField()),
                ('token_text', models.CharField(max_length=255)),
                ('collation', models.ForeignKey(on_delete=models.CASCADE, to='collation.collation', to_field='_djazzkit_id')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('collation', 'witness_id', 'token_index'), name='uniq_collation_token_position')],
            },
        ),
        migrations.CreateModel(
            name='CollationWitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('witness_id', models.CharField(max_length=64)),
                ('source_version', models.CharField(blank=True, default='', max_length=64)),
                ('content', models.TextField(blank=True, default='')),
                ('position', models.IntegerField(default=0)),
                ('collation', models.ForeignKey(on_delete=models.CASCADE, to='collation.collation', to_field='_djazzkit_id')),
                ('transcription', models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, to='transcription.transcription', to_field='_djazzkit_id')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('collation', 'witness_id'), name='uniq_collation_witness')],
            },
        ),
    ]
