# Generated by Django 6.0.2 on 2026-03-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collation',
            name='group_path',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
    ]
