# Generated by Django 6.0.2 on 2026-03-05 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0002_collation_group_path'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collations', to='project.project', to_field='_djazzkit_id'),
        ),
        migrations.AddField(
            model_name='collation',
            name='sort_key',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='collation',
            name='status',
            field=models.CharField(blank=True, default='draft', max_length=32),
        ),
    ]
