# Generated by Django 6.0.2 on 2026-03-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0003_collation_project_collation_sort_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collation',
            name='delete_me',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
