# Generated by Django 6.0.2 on 2026-03-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0004_collation_delete_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collation',
            name='delete_me',
        ),
    ]
