import type { ClassifiedReading } from './collation-types';
import { cloneUnitDecisions, type UnitDecisions } from './collation-decisions';
import { getReadingFamilyKey } from './collation-reading-proposal';

type Readings = ClassifiedReading[];

function makeWitnessGroups(witnessIds: string[]) {
	return witnessIds.length > 0 ? [{ id: crypto.randomUUID(), witnessIds: [...witnessIds] }] : [];
}

export function countLabel(count: number, noun: string): string {
	return `${count} ${noun}${count === 1 ? '' : 'es'}`;
}

/** Deduped attesting subset, in order. */
function attestingSelection(readings: Readings, witnessIds: string[]): string[] {
	const seen = new Set<string>();
	return witnessIds.filter(witnessId => {
		if (seen.has(witnessId)) return false;
		seen.add(witnessId);
		return readings.some(reading => reading.witnessIds.includes(witnessId));
	});
}

function dropEmptiedReadings(before: Readings, after: Readings, keepReadingId: string): Readings {
	const hadWitnesses = new Set(
		before.filter(reading => reading.witnessIds.length > 0).map(reading => reading.id)
	);
	const parentIds = new Set(
		after.map(reading => reading.parentReadingId).filter((id): id is string => id !== null)
	);
	return after.filter(
		reading =>
			reading.id === keepReadingId ||
			reading.witnessIds.length > 0 ||
			!hadWitnesses.has(reading.id) ||
			parentIds.has(reading.id)
	);
}

function withoutWitnesses(readings: Readings, witnessIds: Set<string>): Readings {
	return readings.map(reading => {
		const kept = reading.witnessIds.filter(witnessId => !witnessIds.has(witnessId));
		return kept.length === reading.witnessIds.length
			? reading
			: { ...reading, witnessIds: kept };
	});
}

function nextSiblingOrder(readings: Readings, parentReadingId: string | null): number {
	return (
		Math.max(
			-1,
			...readings
				.filter(reading => reading.parentReadingId === parentReadingId)
				.map(reading => reading.order)
		) + 1
	);
}

export function moveWitnesses(readings: Readings, witnessIds: string[], targetReadingId: string) {
	const target = readings.find(reading => reading.id === targetReadingId);
	if (!target) return { ok: false as const, error: 'reading-not-found' as const };
	const selected = attestingSelection(readings, witnessIds);
	if (selected.length === 0)
		return { ok: false as const, error: 'no-attesting-witnesses' as const };

	const moving = selected.filter(witnessId => !target.witnessIds.includes(witnessId));
	if (moving.length === 0) return { ok: true as const, moving, readings };
	const updated = withoutWitnesses(readings, new Set(moving)).map(reading =>
		reading.id === target.id
			? { ...reading, witnessIds: [...target.witnessIds, ...moving] }
			: reading
	);
	return {
		ok: true as const,
		moving,
		readings: dropEmptiedReadings(readings, updated, target.id),
	};
}

/** New reading inherits the first witness's text, not a blank. */
export function splitWitnesses(
	readings: Readings,
	witnessIds: string[],
	parentReadingId: string | null
) {
	const selected = attestingSelection(readings, witnessIds);
	if (selected.length === 0)
		return { ok: false as const, error: 'no-attesting-witnesses' as const };
	if (parentReadingId !== null && !readings.some(reading => reading.id === parentReadingId)) {
		return { ok: false as const, error: 'reading-not-found' as const };
	}

	const selectedSet = new Set(selected);
	const sources = readings.filter(reading =>
		reading.witnessIds.some(witnessId => selectedSet.has(witnessId))
	);
	// Whole-reading split records no distinction.
	if (
		sources.length === 1 &&
		sources[0].witnessIds.every(witnessId => selectedSet.has(witnessId))
	) {
		return { ok: false as const, error: 'whole-reading' as const };
	}

	const readingId = crypto.randomUUID();
	const updated: Readings = [
		...withoutWitnesses(readings, selectedSet),
		{
			...sources[0],
			id: readingId,
			order: nextSiblingOrder(readings, parentReadingId),
			label: '',
			witnessIds: selected,
			witnessGroups: makeWitnessGroups(selected),
			parentReadingId,
			isSubreading: parentReadingId !== null,
			autoGenerated: false,
		},
	];
	return {
		ok: true as const,
		readingId,
		selected,
		readings: dropEmptiedReadings(readings, updated, readingId),
	};
}

/** Target keeps text; merged subreadings follow witnesses. */
export function mergeReadingsInto(
	readings: Readings,
	sourceReadingIds: string[],
	targetReadingId: string
) {
	const target = readings.find(reading => reading.id === targetReadingId);
	if (!target) return { ok: false as const, error: 'reading-not-found' as const };

	const sourceIds = new Set(sourceReadingIds.filter(id => id !== targetReadingId));
	if (sourceIds.size === 0) return { ok: false as const, error: 'nothing-to-merge' as const };
	if ([...sourceIds].some(id => !readings.some(reading => reading.id === id))) {
		return { ok: false as const, error: 'reading-not-found' as const };
	}
	// Survivor would dangle from a removed reading.
	let ancestorId = target.parentReadingId;
	while (ancestorId) {
		if (sourceIds.has(ancestorId))
			return { ok: false as const, error: 'target-under-source' as const };
		ancestorId = readings.find(reading => reading.id === ancestorId)?.parentReadingId ?? null;
	}

	const witnessIds = [...target.witnessIds];
	for (const reading of readings) {
		if (!sourceIds.has(reading.id)) continue;
		for (const witnessId of reading.witnessIds) {
			if (!witnessIds.includes(witnessId)) witnessIds.push(witnessId);
		}
	}

	const updated = readings
		.filter(reading => !sourceIds.has(reading.id))
		.map(reading => {
			if (reading.id === target.id) return { ...reading, witnessIds };
			if (reading.parentReadingId && sourceIds.has(reading.parentReadingId)) {
				return { ...reading, parentReadingId: target.id, isSubreading: true };
			}
			return reading;
		});
	return { ok: true as const, sourceIds, readings: updated };
}

/** Attachment is a decision: it must follow witnesses into the survivor. */
export function redirectSubreadingAttachments(
	decisions: UnitDecisions | undefined,
	sourceIds: Set<string>,
	targetReadingId: string
): UnitDecisions | undefined {
	const attachments = decisions?.subreadingOf ?? {};
	const reattached = Object.values(attachments).some(
		mainReadingId => mainReadingId !== null && sourceIds.has(mainReadingId)
	);
	if (!reattached) return undefined;
	const next = cloneUnitDecisions(decisions);
	next.subreadingOf = Object.fromEntries(
		Object.entries(attachments).map(([readingId, mainReadingId]) => [
			readingId,
			mainReadingId !== null && sourceIds.has(mainReadingId)
				? targetReadingId
				: mainReadingId,
		])
	);
	return next;
}

export function parentAttachmentError(
	readings: Readings,
	readingId: string,
	parentReadingId: string | null
): 'reading-not-found' | 'self-attachment' | 'cycle' | null {
	const target = readings.find(reading => reading.id === readingId);
	const parent = parentReadingId
		? (readings.find(reading => reading.id === parentReadingId) ?? null)
		: null;
	if (!target || (parentReadingId !== null && !parent)) return 'reading-not-found';
	if (parentReadingId === readingId) return 'self-attachment';

	let ancestor = parent;
	while (ancestor) {
		if (ancestor.id === readingId) return 'cycle';
		ancestor = ancestor.parentReadingId
			? (readings.find(reading => reading.id === ancestor?.parentReadingId) ?? null)
			: null;
	}
	return null;
}

export function promoteFamilyParent(readings: Readings, readingId: string): Readings | null {
	const target = readings.find(reading => reading.id === readingId);
	if (!target) return null;
	const familyKey = getReadingFamilyKey(target);
	const family = readings.filter(reading => getReadingFamilyKey(reading) === familyKey);
	if (family.length < 2) return null;
	return readings.map(reading => {
		if (getReadingFamilyKey(reading) !== familyKey) return reading;
		if (reading.id === readingId) {
			return {
				...reading,
				order: Math.min(...family.map(member => member.order)),
				parentReadingId: null,
				isSubreading: false,
				autoGenerated: false,
			};
		}
		return {
			...reading,
			parentReadingId: readingId,
			isSubreading: !reading.isOmission && !reading.isLacuna,
		};
	});
}

export function withReadingText(readings: Readings, readingId: string, text: string): Readings {
	const nextText = text.trim() || null;
	return readings.map(reading =>
		reading.id === readingId
			? {
					...reading,
					text: nextText,
					normalizedText: nextText,
					isOmission: false,
					isLacuna: false,
				}
			: reading
	);
}

export function withNormalizedReadingText(
	readings: Readings,
	readingId: string,
	text: string
): Readings {
	const nextNormalized = text.trim() || null;
	return readings.map(reading => {
		if (reading.id !== readingId) return reading;
		const shouldMirrorText =
			reading.parentReadingId === null &&
			(reading.text === reading.normalizedText || reading.text === null);
		return {
			...reading,
			text: shouldMirrorText ? nextNormalized : reading.text,
			normalizedText: nextNormalized,
			isOmission: false,
			isLacuna: false,
		};
	});
}

export function emptyReading(
	readings: Readings,
	parentReadingId: string | null
): ClassifiedReading {
	return {
		id: crypto.randomUUID(),
		order: nextSiblingOrder(readings, parentReadingId),
		label: '',
		text: null,
		normalizedText: null,
		witnessIds: [],
		witnessGroups: [],
		isOmission: false,
		isLacuna: false,
		readingType: null,
		certainty: null,
		parentReadingId,
		isSubreading: parentReadingId !== null,
		autoGenerated: false,
		derivedFromRuleIds: [],
	};
}

/** Own witnesses plus every subreading in the chain; guards deletion. */
export function attestingWitnessIds(readings: Readings, readingId: string): string[] {
	const chain = new Set<string>([readingId]);
	for (let grew = true; grew;) {
		grew = false;
		for (const reading of readings) {
			if (chain.has(reading.id)) continue;
			if (reading.parentReadingId === null || !chain.has(reading.parentReadingId)) continue;
			chain.add(reading.id);
			grew = true;
		}
	}
	const witnessIds: string[] = [];
	const seen = new Set<string>();
	for (const reading of readings) {
		if (!chain.has(reading.id)) continue;
		for (const witnessId of reading.witnessIds) {
			if (seen.has(witnessId)) continue;
			seen.add(witnessId);
			witnessIds.push(witnessId);
		}
	}
	return witnessIds;
}

export function withoutReading(readings: Readings, readingId: string): Readings | null {
	const target = readings.find(reading => reading.id === readingId);
	if (!target || attestingWitnessIds(readings, readingId).length > 0) return null;
	return readings
		.filter(reading => reading.id !== readingId)
		.map(reading =>
			reading.parentReadingId === readingId
				? { ...reading, parentReadingId: null, isSubreading: false }
				: reading
		);
}

function reorderReadingGroup(
	readings: Readings,
	groupParentId: string | null,
	readingId: string,
	targetIndex: number
): Readings {
	const siblings = readings
		.filter(reading => reading.parentReadingId === groupParentId)
		.sort((a, b) => a.order - b.order);
	const sourceIndex = siblings.findIndex(reading => reading.id === readingId);
	if (sourceIndex === -1) return readings;
	const clampedTargetIndex = Math.max(0, Math.min(targetIndex, siblings.length - 1));
	if (clampedTargetIndex === sourceIndex) return readings;
	const nextSiblings = [...siblings];
	const [moved] = nextSiblings.splice(sourceIndex, 1);
	if (!moved) return readings;
	nextSiblings.splice(clampedTargetIndex, 0, moved);
	const orderById = new Map(nextSiblings.map((reading, index) => [reading.id, index] as const));
	return readings.map(reading =>
		reading.parentReadingId === groupParentId && orderById.has(reading.id)
			? { ...reading, order: orderById.get(reading.id) ?? reading.order }
			: reading
	);
}

function sortedSiblings(readings: Readings, reading: ClassifiedReading): Readings {
	return readings
		.filter(entry => entry.parentReadingId === reading.parentReadingId)
		.sort((a, b) => a.order - b.order);
}

export function moveReadingByOffsetIn(readings: Readings, readingId: string, offset: number) {
	const reading = readings.find(entry => entry.id === readingId);
	if (!reading) return { ok: false as const, error: 'reading-not-found' as const };
	const siblings = sortedSiblings(readings, reading);
	const currentIndex = siblings.findIndex(entry => entry.id === readingId);
	if (currentIndex === -1) return { ok: false as const, error: 'reading-not-found' as const };
	const targetIndex = currentIndex + offset;
	if (targetIndex < 0 || targetIndex > siblings.length - 1) {
		return { ok: false as const, error: 'at-boundary' as const };
	}
	return {
		ok: true as const,
		readings: reorderReadingGroup(readings, reading.parentReadingId, readingId, targetIndex),
	};
}

export function moveReadingBeforeIn(
	readings: Readings,
	readingId: string,
	targetReadingId: string
) {
	const reading = readings.find(entry => entry.id === readingId);
	const target = readings.find(entry => entry.id === targetReadingId);
	if (!reading || !target) return { ok: false as const, error: 'reading-not-found' as const };
	// Cross-group moves are attachments, not reorderings.
	if (reading.parentReadingId !== target.parentReadingId) {
		return { ok: false as const, error: 'different-group' as const };
	}
	const siblings = sortedSiblings(readings, reading);
	const sourceIndex = siblings.findIndex(entry => entry.id === readingId);
	const targetIndex = siblings.findIndex(entry => entry.id === targetReadingId);
	if (sourceIndex === -1 || targetIndex === -1) {
		return { ok: false as const, error: 'reading-not-found' as const };
	}
	return {
		ok: true as const,
		readings: reorderReadingGroup(
			readings,
			reading.parentReadingId,
			readingId,
			sourceIndex < targetIndex ? targetIndex - 1 : targetIndex
		),
	};
}
