# Generated by Django 4.1.5 on 2023-02-27 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='data',
            field=models.TextField(default=''),
        ),
    ]
