# Generated by Django 4.1.5 on 2023-02-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobstatus_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobstatus',
            name='textual_flow',
            field=models.BooleanField(default=False),
        ),
    ]
