# Generated by Django 4.1.7 on 2023-05-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_jobstatus_textual_flow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='', help_text='The public name you would like to be displayed with your apparatus if you choose to publish it.', max_length=50, unique=True),
        ),
    ]
