# Generated by Django 4.2.11 on 2024-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_unread_announcements',
            field=models.BooleanField(default=True),
        ),
    ]
