export {
	deleteAllPageCanvasLinks,
	deleteCanvasAnnotation,
	deleteManifestSource,
	deleteManifestSourceLinks,
	deletePageCanvasLink,
	deletePageCanvasLinksForPage,
	ensureManifestSource,
	findLinkedPageForCanvas,
	getCanvasAnnotation,
	getManifestSource,
	listCanvasAnnotations,
	listManifestSources,
	listManifestSourcesForUrl,
	listPageCanvasLinks,
	savePageCanvasLinks,
	upsertCanvasAnnotation,
	upsertPageCanvasLink,
} from '$lib/client/db/client';
