# Generated by Django 6.0.2 on 2026-03-02 20:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('siglum', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('format', models.CharField(default='normalized_ast_v1', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('tags', models.JSONField(default=list)),
                ('transcriber', models.CharField(blank=True, default='', max_length=255)),
                ('repository', models.CharField(blank=True, default='', max_length=255)),
                ('settlement', models.CharField(blank=True, default='', max_length=255)),
                ('language', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'ordering': ['-_djazzkit_updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranscriptionCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('format', models.CharField(default='normalized_ast_v1', max_length=32)),
                ('payload', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transcription', models.ForeignKey(on_delete=models.CASCADE, to='transcription.transcription', to_field='_djazzkit_id')),
            ],
            options={
                'ordering': ['-_djazzkit_updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TranscriptionVerseIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_djazzkit_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_djazzkit_rev', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('_djazzkit_deleted', models.BooleanField(db_index=True, default=False)),
                ('_djazzkit_updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('verse_identifier', models.CharField(db_index=True, max_length=128)),
                ('book', models.CharField(blank=True, default='', max_length=64)),
                ('chapter', models.CharField(blank=True, default='', max_length=32)),
                ('verse', models.CharField(blank=True, default='', max_length=32)),
                ('last_indexed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('transcription', models.ForeignKey(on_delete=models.CASCADE, to='transcription.transcription', to_field='_djazzkit_id')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transcription', 'verse_identifier'), name='uniq_transcription_verse_presence')],
            },
        ),
    ]
