# Generated by Django 4.1.5 on 2023-02-01 19:36

import cbgm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cbgm_Db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('db_name', models.CharField(max_length=64)),
                ('db_file', models.FileField(upload_to=cbgm.models.user_directory_path)),
                ('amount', models.SmallIntegerField(choices=[(0, 'Verse'), (1, 'Section'), (2, 'Full')], default=0)),
                ('threshold', models.SmallIntegerField(default=1, help_text='Minimum number of readings for a witness to be included.')),
                ('trivial_types', models.CharField(blank=True, help_text='List of reading types to treat as agreeing with their parent. E.g., "subr err"', max_length=255, null=True)),
                ('ignore_types', models.CharField(blank=True, help_text='List of reading types to ignore. E.g., "lac defi"', max_length=255, null=True)),
                ('ignore_suffixes', models.CharField(blank=True, help_text='List of witness suffixes to strip away. E.g., "* T V"', max_length=255, null=True)),
                ('merge_splits', models.BooleanField(default=False)),
                ('use_classic_rules', models.BooleanField(default=False)),
                ('witnesses', models.JSONField(default=list, null=True)),
                ('app_labels', models.JSONField(default=list, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'db_name')},
            },
        ),
    ]
