# Generated by Django 4.2.11 on 2024-05-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbgm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbgm_db',
            name='remove_rdg_types_before_import',
            field=models.JSONField(default=list, null=True),
        ),
    ]
