# Generated by Django 4.1.5 on 2023-01-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('markdown', models.TextField()),
                ('order', models.SmallIntegerField(default=0)),
                ('html', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
