# Generated by Django 4.1.7 on 2023-11-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
