# Generated by Django 4.2.11 on 2024-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_imageblock_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='H2', max_length=255)),
                ('markdown', models.TextField()),
                ('html', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('time_published', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-time_published',),
            },
        ),
    ]
