# Generated by Django 4.1.5 on 2023-02-19 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='ID')),
                ('basetext_label', models.CharField(max_length=32, verbose_name='Basetext Label')),
                ('basetext', models.TextField()),
                ('number', models.SmallIntegerField()),
                ('indexed_basetext', models.JSONField(blank=True, default=list, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atype', models.CharField(default='main', max_length=9)),
                ('index_from', models.SmallIntegerField()),
                ('index_to', models.SmallIntegerField()),
                ('connectivity', models.SmallIntegerField(default=10)),
                ('ab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='collation.ab')),
            ],
            options={
                'ordering': ['index_from'],
            },
        ),
        migrations.CreateModel(
            name='Collation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rdg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('varSeq', models.SmallIntegerField(default=1)),
                ('rtype', models.CharField(choices=[('0', '-'), ('orth', 'Orthographic'), ('subr', 'Subreading'), ('def', 'Defective'), ('lac', 'Lacuna'), ('ns', 'Nomen Sacrum'), ('emm', 'Emendation'), ('ilc', 'Lectionary Adaptation'), ('insi', 'Insignificant'), ('err', 'Error'), ('om', 'Omission'), ('amb', 'Ambiguous')], default='0', max_length=5, verbose_name='Reading Type')),
                ('text', models.TextField(blank=True, null=True)),
                ('witDetail', models.BooleanField(default=False, verbose_name='Ambiguous Reading')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdgs', to='collation.app')),
                ('target', models.ManyToManyField(blank=True, to='collation.rdg', verbose_name='Potential Readings')),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siglum', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='witnesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('number', models.SmallIntegerField()),
                ('published', models.BooleanField(default=False)),
                ('collation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='collation.collation')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='RdgHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=5)),
                ('rtype', models.CharField(choices=[('0', '-'), ('orth', 'Orthographic'), ('subr', 'Subreading'), ('def', 'Defective'), ('lac', 'Lacuna'), ('ns', 'Nomen Sacrum'), ('emm', 'Emendation'), ('ilc', 'Lectionary Adaptation'), ('insi', 'Insignificant'), ('err', 'Error'), ('om', 'Omission'), ('amb', 'Ambiguous')], default='0', max_length=5, verbose_name='Reading Type')),
                ('text', models.TextField(blank=True, null=True)),
                ('rdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='collation.rdg')),
                ('wit', models.ManyToManyField(blank=True, related_name='history_rdgs', to='collation.witness', verbose_name='Witnesses')),
            ],
            options={
                'ordering': ['-modified'],
            },
        ),
        migrations.AddField(
            model_name='rdg',
            name='wit',
            field=models.ManyToManyField(blank=True, related_name='rdgs', to='collation.witness', verbose_name='Witnesses'),
        ),
        migrations.CreateModel(
            name='Arc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs', to='collation.app')),
                ('rdg_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs_from', to='collation.rdg')),
                ('rdg_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arcs_to', to='collation.rdg')),
            ],
        ),
        migrations.AddField(
            model_name='ab',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abs', to='collation.section'),
        ),
        migrations.AddIndex(
            model_name='witness',
            index=models.Index(fields=['siglum'], name='collation_w_siglum_6902b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='witness',
            unique_together={('siglum', 'user')},
        ),
        migrations.AddConstraint(
            model_name='arc',
            constraint=models.UniqueConstraint(fields=('app', 'rdg_from', 'rdg_to'), name='unique_arc'),
        ),
    ]
