# Generated by Django 4.1.5 on 2023-02-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdg',
            name='rtype',
            field=models.CharField(choices=[('0', '-'), ('orth', 'Orthographic'), ('subr', 'Subreading'), ('def', 'Defective'), ('lac', 'Lacuna'), ('ns', 'Nomen Sacrum'), ('emm', 'Emendation'), ('ilc', 'Lectionary Adaptation'), ('insi', 'Insignificant'), ('err', 'Error'), ('om', 'Omission'), ('amb', 'Ambiguous')], default='0', max_length=31, verbose_name='Reading Type'),
        ),
    ]
