# Generated by Django 4.1.7 on 2023-04-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0003_alter_rdg_name_alter_rdg_rtype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rdg',
            options={'ordering': ['name']},
        ),
    ]
