# Generated by Django 4.1.7 on 2023-04-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0004_alter_rdg_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ab',
            name='name',
            field=models.CharField(max_length=32, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rdg',
            name='rtype',
            field=models.CharField(choices=[('0', '-'), ('amb', 'Ambiguous'), ('corr', 'Correction'), ('def', 'Defective'), ('emm', 'Emendation'), ('err', 'Error'), ('insi', 'Insignificant'), ('lac', 'Lacuna'), ('ilc', 'Lectionary Adaptation'), ('ns', 'Nomen Sacrum'), ('orth', 'Orthographic'), ('om', 'Omission'), ('subr', 'Subreading')], default='0', max_length=64, verbose_name='Reading Type'),
        ),
        migrations.AlterField(
            model_name='rdghistory',
            name='rtype',
            field=models.CharField(choices=[('0', '-'), ('amb', 'Ambiguous'), ('corr', 'Correction'), ('def', 'Defective'), ('emm', 'Emendation'), ('err', 'Error'), ('insi', 'Insignificant'), ('lac', 'Lacuna'), ('ilc', 'Lectionary Adaptation'), ('ns', 'Nomen Sacrum'), ('orth', 'Orthographic'), ('om', 'Omission'), ('subr', 'Subreading')], default='0', max_length=5, verbose_name='Reading Type'),
        ),
    ]
