# Generated by Django 4.1.7 on 2023-05-09 03:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collation', '0005_alter_ab_name_alter_rdg_rtype_alter_rdghistory_rtype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collation',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='collation',
            index=models.Index(fields=['name'], name='collation_c_name_545e77_idx'),
        ),
    ]
