# Generated by Django 4.1.7 on 2023-11-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0008_alter_rdghistory_rtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdghistory',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
