# Generated by Django 4.1.7 on 2023-11-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0009_alter_rdghistory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='collation',
            name='slug',
            field=models.SlugField(blank=True, max_length=84, null=True),
        ),
    ]
