# Generated by Django 4.1.7 on 2023-11-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0010_collation_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slugname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, default='name', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('collation', 'name')},
        ),
    ]
