# Generated by Django 4.1.7 on 2023-11-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0011_section_slugname_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ab',
            name='slugname',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
