# Generated by Django 4.1.7 on 2023-11-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0012_ab_slugname'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='slugname',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
