# Generated by Django 4.1.7 on 2024-01-05 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0015_app_deleted_app_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_names', models.JSONField(blank=True, default=list, null=True)),
                ('ab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collation_config', to='collation.ab')),
                ('basetext', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_basetext_for', to='collation.witness')),
                ('witnesses', models.ManyToManyField(related_name='collation_configs', to='collation.witness')),
            ],
        ),
    ]
