# Generated by Django 4.2.11 on 2024-05-10 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collation', '0017_alter_collationconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_pk', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('collation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_indexes', to='collation.collation')),
            ],
        ),
        migrations.CreateModel(
            name='RdgIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdg_pk', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('rtype', models.CharField(max_length=64)),
                ('app_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdg_indexes', to='collation.appindex')),
                ('witnesses', models.ManyToManyField(related_name='rdg_indexes', to='collation.witness')),
            ],
        ),
    ]
